#
# Node.js Developer Dockerfile
#
# https://github.com/metagen/nodejs-developer
#

# Pull base image.
FROM dockerfile/nodejs

# Define working directory.

WORKDIR /home
VOLUME ["/home"]

# Define default command.
CMD ["bash"]
